# server port config
server:
  port: 8001


# db connection info & fileupload config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today/zzclub
    username: zwozwoclub
    password: zwozwoclub
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/salary/

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging Level
logging:
  level:
    root: info

## 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  add-resource-locations: classpath:/static/
  add-resource-handler: /**

  image-dir: src/main/resources/static
  image-url: http://localhost:8001/

# Generate jws key // 토큰 유효 시간(밀리세컨)
jwt:
  key: a67wzId2jEVOEGH5Gy8wyrQtds3U5xULPLrbzw17UL0=
  time: 864000000

springdoc:
  packages-to-scan: com.wisehr.wisehr
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8