###받은 결재 (mem_code) 완료
GET http://localhost:8001/approval/receivedpayment/2
Content-Type: application/json
Accept: */*

###보낸 결재 (mem_code) 완료
GET http://localhost:8001/approval/sendpayment/1
Content-Type: application/json
Accept: */*

### insert Test
POST http://localhost:8001/approval/submit
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "appState": "반려",
  "appDate": "2024-02-01",
  "approval" : {
    "payCode" :"pay12"
  },
  "paymentMember": {
    "memCode" : 1
  }
}

###서류 요청 상신
POST http://localhost:8001/approval/requestdocument
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="reqKind"

재직 증명서

--WebAppBoundary
Content-Disposition: form-data; name="reqUse"

대출 신청에 사용

--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

3

--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-02-27

--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

서류 요청
--WebAppBoundary


###퇴직 요청 상신
POST http://localhost:8001/approval/retired
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="tirDate"

2024-03-21

--WebAppBoundary
Content-Disposition: form-data; name="tirContents"

고생 많으셨습니다.

--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

3

--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-02-27

--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

퇴직 신청
--WebAppBoundary

###스케줄정정 상신
POST http://localhost:8001/approval/schedule
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="eshName"

쉴래용

--WebAppBoundary
Content-Disposition: form-data; name="eshStartDate"

2024-03-21

--WebAppBoundary
Content-Disposition: form-data; name="eshEndDate"

2024-03-21

--WebAppBoundary
Content-Disposition: form-data; name="eshContents"

쉴거라구요!!!!

--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

1

--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-02-29

--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

스케줄 정정
--WebAppBoundary

###출퇴근정정 상신
POST http://localhost:8001/approval/commute
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="ediKind"

결근

--WebAppBoundary
Content-Disposition: form-data; name="ediName"

저 이때 출근 했어요..

--WebAppBoundary
Content-Disposition: form-data; name="ediContents"

cctv 확인 가야겠어요

--WebAppBoundary
Content-Disposition: form-data; name="ediDate"

2024-01-20

--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

1

--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-01-23

--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

출퇴근 정정
--WebAppBoundary


###연차결재상신
POST http://localhost:8001/approval/annual
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="vacKind"

연차
--WebAppBoundary
Content-Disposition: form-data; name="vacName"

연차 갈게요
--WebAppBoundary
Content-Disposition: form-data; name="vacContents"

화이팅 화이팅
--WebAppBoundary
Content-Disposition: form-data; name="vacStartDate"

2024-07-18
--WebAppBoundary
Content-Disposition: form-data; name="vacEndDate"

2024-07-18
--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-03-21
--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

연차 신청
--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

3
--WebAppBoundary
Content-Disposition: form-data; name="approvalFile"; filename="plus.png"

< plus.png
--WebAppBoundary


###결재 승인 로직
PUT http://localhost:8001/approval/complete
Content-Type: application/json
Accept: */*

{
  "appCode": "app5",
  "appDate": "2024-01-31",
  "appState": "승인",
  "appComment": "재밌게 놀다와~!"
}