###받은 결재 (mem_code) 완료
GET http://localhost:8001/approval/receivedpayment/2
Content-Type: application/json
Accept: */*

###보낸 결재 (mem_code) 완료
GET http://localhost:8001/approval/sendpayment/1
Content-Type: application/json
Accept: */*

### insert Test
POST http://localhost:8001/approval/submit
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "appState": "반려",
  "appDate": "2024-02-01",
  "approval" : {
    "payCode" :"pay12"
  },
  "paymentMember": {
    "memCode" : 1
  }
}


###연차결재상신
POST http://localhost:8001/approval/annual
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="vacKind"

연차
--WebAppBoundary
Content-Disposition: form-data; name="vacName"

연차 갈게요
--WebAppBoundary
Content-Disposition: form-data; name="vacContents"

화이팅 화이팅
--WebAppBoundary
Content-Disposition: form-data; name="vacStartDate"

2024-01-18
--WebAppBoundary
Content-Disposition: form-data; name="vacEndDate"

2024-11-18
--WebAppBoundary
Content-Disposition: form-data; name="approval.payCode"

pay3
--WebAppBoundary
Content-Disposition: form-data; name="approval.payDate"

2024-01-15
--WebAppBoundary
Content-Disposition: form-data; name="approval.payKind"

연차 신청
--WebAppBoundary
Content-Disposition: form-data; name="approval.approvalMember.memCode"

240130003
--WebAppBoundary
Content-Disposition: form-data; name="paymentFile"; filename="pikachu.png"

< pikachu.png
--WebAppBoundary