###공지 댓글 작성
POST http://localhost:8001/comment/comment
Content-Type: application/json
Accept: */*

{
  "comContents": "근무하기시렁 배벅벅.",
  "comDate": "2024-02-01",
  "comMember": {
    "memCode": 2
  },
  "comDeleteState": "N",
  "notCode": {
    "notCode": "not6"
  }
}


###공지댓글전체조회
GET http://localhost:8001/comment/allComment
Content-Type: application/json
Accept: */*

###글코드로 댓글 조회
GET http://localhost:8001/comment/notCodeSearch?nc=not6
Content-Type: application/json
Accept: */*