###공지 댓글 작성
POST http://localhost:8001/comment/comment
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTA4MzQ3MjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg3NzIzNDd9.hLRjSSZOJNCHgp32VtWMfQDlJMNvOHGERMYnJedMIZw

{
  "comContents": "공지가 따듯하네요..",
  "comDate": "2024-02-15",
  "comMember": {
    "memCode": 3
  },
  "comDeleteState": "N",
  "notCode": {
    "notCode": "not13"
  }
}


###공지댓글전체조회 필요없는기능
GET http://localhost:8001/comment/allComment
Content-Type: application/json
Accept: */*

###글코드로 댓글 조회
GET http://localhost:8001/comment/notCodeSearch?nc=not8
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTA4MzQ3MjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg3NzIzNDd9.hLRjSSZOJNCHgp32VtWMfQDlJMNvOHGERMYnJedMIZw
