### 부서 조회

GET http://localhost:8001/org/list
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3Nzg2NTI0MzAyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODY1MDUyNH0.b6EX_Ddhliifk8L07Bpisb3HwqSVHOkn2UU5uYdkSzY

### 상위 부서 조회

GET http://localhost:8001/org/repList
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3Nzg2NTI0MzAyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODY1MDUyNH0.b6EX_Ddhliifk8L07Bpisb3HwqSVHOkn2UU5uYdkSzY

### 부서 생성

POST http://localhost:8001/org/insertOrgDep
Content-Type: application/json
Accept: */*

{
  "depName": "호흡기내과2팀",
  "refDepCode": 4
}

### 부서명 수정

PUT http://localhost:8001/org/modifyOrgDep
Content-Type: application/json
Accept: */*

{
  "depCode": 17,
  "depName": "호흡기내과3팀"

}

### 부서별 멤버 전체 조회(트리, 카드 조회)

GET http://localhost:8001/org/AllMemOfDep
Content-Type: application/json
Accept: */*


### 부서 삭제(delete 아닌 status Y 및 각 회원정보 null로 변경)

PUT http://localhost:8001/org/deleteOrgDep
Content-Type: application/json
Accept: */*

{
  "depCode": 17
}

### 부서 개별 조회

GET http://localhost:8001/org/list/6
Content-Type: application/json
Accept: */*



### 전체 멤버 조회(페이징)

GET http://localhost:8001/org/memberList?offset=2
Content-Type: application/json
Accept: */*


### 부서에 멤버 추가

PUT http://localhost:8001/org/insertMember/6
Content-Type: application/json
Accept: */*

  [1, 4]


### 중간관리자 지정
PUT http://localhost:8001/org/updateRole/
Content-Type: application/json
Accept: */*

{
  "memCode": 4,
  "depCode": 6
}

### 트리뷰조회
GET http://localhost:8001/org/treeView
Content-Type: application/json
Accept: */*

