### 부서 조회

GET http://localhost:8001/org/list
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ

### 상위 부서 조회

GET http://localhost:8001/org/repList
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


### 부서 생성

POST http://localhost:8001/org/insertOrgDep
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


{
  "depName": "호흡기내과3팀",
  "refDepCode": 4
}

### 부서명 수정

PUT http://localhost:8001/org/modifyOrgDep
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


{
  "depCode": 16,
  "depName": "호흡기내과2팀",
  "refDepCode": 3
}

### 부서별 멤버 전체 조회(트리, 카드 조회)

GET http://localhost:8001/org/AllMemOfDep
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ



### 부서 삭제(delete 아닌 status Y 및 각 회원정보 null로 변경)

PUT http://localhost:8001/org/deleteOrgDep
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


{
  "depCode": 17
}

### 부서 개별 조회

GET http://localhost:8001/org/list/5
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ




### 전체 멤버 조회(페이징)

GET http://localhost:8001/org/memberList?offset=2
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ



### 부서에 멤버 추가

PUT http://localhost:8001/org/insertMember/13
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


  [240207003, 240207010, 240207011]


### 멤버권한 지정
PUT http://localhost:8001/org/updateRole/
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ

{
  "memCode": 240207020,
  "memRole": "ADMIN"
}

### 트리뷰조회
GET http://localhost:8001/org/treeView
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ


### 이름으로 검색
GET http://localhost:8001/org/nameSearch?n=유
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTYwMjYwMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDg4MjQyNjB9.7izWw88VrlXXxhBeoy8Zv9h2h5XVeDN83FrTDsIiCgQ

