### 결재 상태 조회

GET http://localhost:8001/main/approvalCount/2
Content-Type: application/json
Accept: */*


### 달력 전체 조회

GET http://localhost:8001/main/searchMonth
Content-Type: application/json
Accept: */*

{
  "memCode": 3
}
