### 회원 상세 조회
GET http://localhost:8001/myPage/searchMem/4
Content-Type: application/json
Accept: */*

### 학위 상세 조회
GET http://localhost:8001/myPage/searchDegree/1
Content-Type: application/json
Accept: */*

### 자격 상세 조회
GET http://localhost:8001/myPage/searchCer/1
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MzcxMTczNTIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODIzNTE3M30.I2To74tCzqxGcPnhVLPkdxuefnimCVtwh1qfhChhFRk

### 경력 상세 조회
GET http://localhost:8001/myPage/searchCareer/1
Content-Type: application/json
Accept: */*

### 출퇴근 상세 조회
GET http://localhost:8001/myPage/attendance/2/2024-01-01
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MzcxMTczNTIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODIzNTE3M30.I2To74tCzqxGcPnhVLPkdxuefnimCVtwh1qfhChhFRk


### 서류함 상세 조회
GET http://localhost:8001/myPage/document/1
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MzcxMTczNTIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODIzNTE3M30.I2To74tCzqxGcPnhVLPkdxuefnimCVtwh1qfhChhFRk


### 소유/소멸예정 연차 조회
GET http://localhost:8001/myPage/ownAnnual/2
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MzcxMTczNTIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODIzNTE3M30.I2To74tCzqxGcPnhVLPkdxuefnimCVtwh1qfhChhFRk


### 연차 사용 이력 조회
GET http://localhost:8001/myPage/annualHistory/3
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MzcxMTczNTIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODIzNTE3M30.I2To74tCzqxGcPnhVLPkdxuefnimCVtwh1qfhChhFRk


### 회원 정보 수정
PUT http://localhost:8001/myPage/updateMem
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memCode"

1
--WebAppBoundary
Content-Disposition: form-data; name="memPhone"

010-9999-9999
--WebAppBoundary
Content-Disposition: form-data; name="memEmail"

sujung@gmail.com
--WebAppBoundary
Content-Disposition: form-data; name="memAddress"

수정된 주소
--WebAppBoundary
Content-Disposition: form-data; name="memBirth"

1999-09-09

### 서명 등록
POST http://localhost:8001/myPage/insertSign
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memCode"

1
--WebAppBoundary
Content-Disposition: form-data; name="productImage"; filename="pikachu.png"

< ./pikachu.png

### 서명 수정
PUT http://localhost:8001/myPage/updateSign
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memCode"

1
--WebAppBoundary
Content-Disposition: form-data; name="productImage"; filename="pikachu2.png"

< ./pikachu2.png
