### 공지 등록
POST http://localhost:8001/notice/notice
Content-Type: application/json
Accept: */*

{
  "notCode": "not5",
  "notName": "공지등록테스트",
  "notComment": "공지내용작성",
  "notView": "1",
  "notCreateDate": "2023-01-11",
  "memCode": 1,
  "notDeleteStatus": "N"
}




###공지 조회
GET http://localhost:8001/notice/allNoticeSearch

###공지제목 조회
GET http://localhost:8001/notice/titleSearch?t=1

