
###급여조회 - 연도별로 조회, 첫페이지엔 이번년도 조회
GET http://localhost:8001/pay/payList/2/2023
Content-Type: application/json
Accept: */*

### 연도 select태그 입력값 가져오기(입사년도부터 올해까지)
GET http://localhost:8001/pay/pay-List2/2
Content-Type: application/json
Accept: */*

//공제사항 계산
//매월 25일에 직원 급여 계산하여 급여 테이블에 insert(근무일에 따라 급여 계산)

