### 일정 등록 - 일정 테이블 insert -> 근무 패턴 요일 테이블 insert
POST http://localhost:8001/schedule/schedule
Content-Type: application/json
Accept: */*

{
  "scheduleDTO": {
    "schType": "테스트",
    "schStartDate": "2024-01-01",
    "schEndDate": "2024-01-30",
    "schColor": "#ffffff",
    "schDeleteStatus": "N",
    "wokCode": 16
  },
  "patternDayDTO": [{
    "dayCode": 1,
    "wokCode": 16
  },
    {
      "dayCode": 2,
      "wokCode": 16
    }
  ]
}

###일정 수정
PUT http://localhost:8001/schedule/schedule
Content-Type: application/json
Accept: */*

{
  "scheduleDTO": {
    "schCode": "sch10",
    "schType": "테스트",
    "schStartDate": "2024-01-01",
    "schEndDate": "2024-02-15",
    "schColor": "#ffffff",
    "schDeleteStatus": "N",
    "wokCode": 16
  },
  "patternDayDTO": [{
    "dayCode": 5,
    "changeDayCode": 6,
    "wokCode": 16
  },
    {
      "dayCode": 6,
      "changeDayCode": 8,
      "wokCode": 16
    }
  ]
}
###근무패턴 등록
POST http://localhost:8001/schedule/workPattern
Content-Type: application/json
Accept: */*

{
"wokStartTime": "06:00:00",
"wokRestTime": "01:00:00",
"wokEndTime": "13:00:00",
"wokDeleteState": "N"
}

###근무 패턴 수정
PUT http://localhost:8001/schedule/workPattern
Content-Type: application/json
Accept: */*

{
  "wokCode": 15,
  "wokStartTime": "07:01:00",
  "wokRestTime": "01:00:00",
  "wokEndTime": "13:00:00",
  "wokDeleteState": "N"
}

###근무외 일정 등록
POST http://localhost:8001/schedule/etcPattern
Content-Type: application/json
Accept: */*

{
  "memCode": 240130007,
  "etcDate": "2023-02-02",
  "etcKind": 1
}

###근무외 일정 수정
PUT http://localhost:8001/schedule/etcPattern
Content-Type: application/json
Accept: */*

{
  "etcCode": 14,
  "etcDate": "2023-02-15",
  "etcKind": 10
}

###근무 그룹에 사람 등록
POST http://localhost:8001/schedule/allowance
Content-Type: application/json
Accept: */*

{
  "memCode": 240130007,
  "schCode": "sch9"
}

###근무 그룹에 사람 수정
PUT http://localhost:8001/schedule/allowance
Content-Type: application/json
Accept: */*

{
  "memCode": 2,
  "schCode": "sch3",
  "changeSchCode": "sch7"
}

###첫페이지 전체 조회
POST http://localhost:8001/schedule/searchMonth
Content-Type: application/json
Accept: */*

{
  "memCode": 3
}

###조건으로 조회
POST http://localhost:8001/schedule/searchDay
Content-Type: application/json
Accept: */*

{
  "yearMonth": "2024-01-15"
}


