### 일정 등록 - 근무패턴 테이블 insert -> 근무패턴요일 테이블 insert ->일정테이블 insert
POST http://localhost:8001/schedule/insertSchedule
Content-Type: application/json
Accept: */*

{
  "workPatternDTO": {
      "wokStartTime": "06:00:00",
      "wokRestTime": "01:00:00",
      "wokEndTime": "13:00:00",
      "wokDeleteState": "N"
  },
  "scheduleDTO": {
    "schType": "테스트",
    "schStartDate": "2024-01-01",
    "schEndDate": "2024-01-30",
    "schColor": "#ffffff",
    "schDeleteStatus": "N"
  },
  "patternDayDTO": [{
    "dayCode": 1,
    "wokCode": 0
  },
    {
      "dayCode": 2,
      "wokCode": 0
    }
  ]
}


### 이번달 일정 조회 일정이랑 패턴외 일정, 근태 테이블이랑 join한 값


###이전 스케줄 조회 (년-월로 조회 schedule테이블이 아닌 attendance 테이블로 가져옴)
GET http://localhost:8001/schedule/searchPrev/2024-01
Content-Type: application/json
Accept: */*

###다음날 스케줄 조회 - 일정, 근무패턴, 근무패턴요일, 요일, 근무외 일정 조인
#- [ ] 선택한 다른 사람의 일정, 년 - 월 조회
### 일정 패턴 등록 - 근무패턴 테이블 insert -> 근무패턴요일 테이블 insert ->일정테이블 insert
#- [ ] 일정 패턴 수정 - 근무패턴 테이블 update-> 근무패턴요일 테이블 update->일정테이블 update
#- [ ] 일정 패턴 삭제(삭제여부 테이블에 값 Y로 업데이트)
#- [ ] 일정 패턴에 직원 넣기 - 일정기록 테이블 (schedule_allowance), 개인 알림 테이블(per_alarm)에 insert
#- [ ] 근무 일정 - 패턴 출력 - 일정, 근무패턴, 근무패턴요일, 요일, 근무외 일정 조인
#- [ ] 근무 일정 -근무외 일정에 insert