### 직원 정보 등록 - 인사정보 + 사진
POST http://localhost:8001/setting/member
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTc5OTM2NjU3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6ImRqZGRkQGdtYWlsLmNvbSIsIm1lbUNvZGUiOjI0MDIwMjAwNywibWVtTmFtZSI6IuyIoOyfgeydtCIsIm1lbVJvbGUiOiJBRE1JTiIsImV4cCI6MTcwODg0MzkzNn0.gHoJUau4mU_NuEi7zGP-40ALugoyq40g63V8BY1nF68

--WebAppBoundary
Content-Disposition: form-data; name="memName"

역삼역

--WebAppBoundary
Content-Disposition: form-data; name="memPhone"

010-8760-8336

--WebAppBoundary
Content-Disposition: form-data; name="memEmail"

djddd@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="memAddress"

경기도 고양시

--WebAppBoundary
Content-Disposition: form-data; name="memBirth"

1991-01-20

--WebAppBoundary
Content-Disposition: form-data; name="memPassword"

0000

--WebAppBoundary
Content-Disposition: form-data; name="memHireDate"

2024-01-29

--WebAppBoundary
Content-Disposition: form-data; name="memStatus"

N

--WebAppBoundary
Content-Disposition: form-data; name="memRole"

SUPERADMIN


--WebAppBoundary
Content-Disposition: form-data; name="posCode"

3

--WebAppBoundary
Content-Disposition: form-data; name="depCode"

5
--WebAppBoundary
Content-Disposition: form-data; name="profile"; filename="pikachu2.png"

< ./pikachu2.png

###직원 정보 수정
PUT http://localhost:8001/setting/member
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3OTc5OTM2NjU3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6ImRqZGRkQGdtYWlsLmNvbSIsIm1lbUNvZGUiOjI0MDIwMjAwNywibWVtTmFtZSI6IuyIoOyfgeydtCIsIm1lbVJvbGUiOiJBRE1JTiIsImV4cCI6MTcwODg0MzkzNn0.gHoJUau4mU_NuEi7zGP-40ALugoyq40g63V8BY1nF68

--WebAppBoundary
Content-Disposition: form-data; name="memCode"

240215062

--WebAppBoundary
Content-Disposition: form-data; name="memName"

노연지

--WebAppBoundary
Content-Disposition: form-data; name="memPhone"

010-8760-8336

--WebAppBoundary
Content-Disposition: form-data; name="memEmail"

djddd@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="memAddress"

경기도 고양시

--WebAppBoundary
Content-Disposition: form-data; name="memBirth"

1991-01-20

--WebAppBoundary
Content-Disposition: form-data; name="memPassword"

0000

--WebAppBoundary
Content-Disposition: form-data; name="memHireDate"

2024-01-29

--WebAppBoundary
Content-Disposition: form-data; name="memStatus"

N

--WebAppBoundary
Content-Disposition: form-data; name="memRole"

ADMIN

--WebAppBoundary
Content-Disposition: form-data; name="posCode"

3

--WebAppBoundary
Content-Disposition: form-data; name="depCode"

5
--WebAppBoundary
Content-Disposition: form-data; name="profile"; filename="pikachu2.png"

< ./pikachu2.png

--WebAppBoundary
Content-Disposition: form-data; name="profile"; filename="pikachu.png"

< pikachu.png
--WebAppBoundary

### 직원 조회
GET http://localhost:8001/setting/allMemberSearch?offset=1
Content-Type: application/json
Accept: */*

###직원 검색어로 조회
GET http://localhost:8001/setting/search?s=노연지
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA4NTkyMjEzMDQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6Impvc2luMzJAZ21haWwuY29tIiwibWVtQ29kZSI6MjQwMTMwMDEwLCJtZW1OYW1lIjoi7KOg7J247ISxIiwibWVtUm9sZSI6IlNVUEVSQURNSU4iLCJleHAiOjE3MDk0NTYyMTN9.aIucSzgHFQj7I1gY3cWkigl-cbzbyE1cP1q3UlJp430

###직원등록 -부서 조회
GET http://localhost:8001/setting/depSearch
Content-Type: application/json
Accept: */*


###직원등록 -직급 조회
GET http://localhost:8001/setting/position
Content-Type: application/json
Accept: */*

###학위정보등록
POST http://localhost:8001/setting/degree
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "degKind": "학사",
  "degMajor": "공학",
  "degName": "서울대학교",
  "degGraduation": "2024-01-31",
  "degState":"졸업",
  "degAdmissions": "2020-01-01"
}

###학위정보수정
PUT http://localhost:8001/setting/degree
Content-Type: application/json
Accept: */*

{
  "degCode": "deg3",
  "degKind": "학사",
  "degMajor": "공학",
  "degName": "서울대학교교",
  "degGraduation": "2024-01-31",
  "degState":"졸업",
  "degAdmissions": "2020-01-01"
}

###학위파일등록
POST http://localhost:8001/setting/degreeFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="degCode";

deg3
--WebAppBoundary
Content-Disposition: form-data; name="degreeFile"; filename="pikachu.png"

< ./pikachu.png

###자격정보등록
POST http://localhost:8001/setting/certificate
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "cerName": "컴퓨터활용능력",
  "cerKind": "2급",
  "cerDay": "2024-01-31",
  "cerEndDate": null,
  "cerDescription": "비고",
  "cerInstitution": "대한상공회의소"
}

###자격정보수정
PUT http://localhost:8001/setting/certificate
Content-Type: application/json
Accept: */*

{
  "cerCode": "cer5",
  "memCode": 240129002,
  "cerName": "컴퓨터활용능력~",
  "cerKind": "2급",
  "cerDay": "2024-01-31",
  "cerEndDate": null,
  "cerDescription": "비고",
  "cerInstitution": "대한상공회의소"
}

###자격파일등록
POST http://localhost:8001/setting/certificateFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="cerCode";

cer5
--WebAppBoundary
Content-Disposition: form-data; name="certificateFile"; filename="pikachu.png"

< ./pikachu.png

###경력정보등록
POST http://localhost:8001/setting/career
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "crrName": "회사명",
  "crrPosition": "대리",
  "crrStartDate": "2017-01-01",
  "crrEndDate": "2020-01-01",
  "crrState": "Y",
  "crrDescription" : "비고"
}

###경력정보수정
POST http://localhost:8001/setting/career
Content-Type: application/json
Accept: */*

{
  "crrCode": "crr6",
  "memCode": 240129002,
  "crrName": "회사명~",
  "crrPosition": "대리",
  "crrStartDate": "2017-01-01",
  "crrEndDate": "2020-01-01",
  "crrState": "Y",
  "crrDescription" : "비고"
}

###경력파일등록
POST http://localhost:8001/setting/careerFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="crrCode";

crr5
--WebAppBoundary
Content-Disposition: form-data; name="careerFile"; filename="pikachu.png"

< ./pikachu.png

###직원인사정보조회 - 학위, 경력, 자격, 통장
GET http://localhost:8001/setting/searchResourcesInformation/240130007
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3NTQxNjUxOTE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODQwNTY1MX0.cv_yv5ey_mD8lIqO3IvkAIaWys5aln4eJt2exykuPPs

###급여통장 등록
POST http://localhost:8001/setting/salaryFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="salCode";

sal1
--WebAppBoundary
Content-Disposition: form-data; name="salaryFile"; filename="pikachu.png"

< ./pikachu.png

###그외 파일 등록
POST http://localhost:8001/setting/documentFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memCode";

240130007
--WebAppBoundary
Content-Disposition: form-data; name="etcFile"; filename="pikachu.png"

< ./pikachu.png
--WebAppBoundary
Content-Disposition: form-data; name="docAtcKind";

그외 파일



###급여 통장 정보 등록
POST http://localhost:8001/setting/salary
Content-Type: application/json;
Accept: */*

{
  "salNumber": "000000",
  "salBankName": "~은행~",
  "memCode": "240130007"
}

###급여 통장 정보 수정
PUT http://localhost:8001/setting/salary
Content-Type: application/json;
Accept: */*

{
  "salCode": "sal3",
  "salNumber": "000000",
  "salBankName": "은행",
  "memCode": "240130007"
}

###서류함 그외 파일 수정
PUT http://localhost:8001/setting/documentFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memCode";

240130007
--WebAppBoundary
Content-Disposition: form-data; name="etcFile"; filename="pikachu2.png"

< ./pikachu2.png
--WebAppBoundary
Content-Disposition: form-data; name="docAtcCode";

15
--WebAppBoundary
Content-Disposition: form-data; name="docAtcKind";

수정


###학위 파일 수정
PUT http://localhost:8001/setting/degreeFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="degAtcCode";

1
--WebAppBoundary
Content-Disposition: form-data; name="degreeFile"; filename="pikachu2.png"

< ./pikachu2.png

###경력 파일 수정
PUT http://localhost:8001/setting/careerFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="crrAtcCode";

1
--WebAppBoundary
Content-Disposition: form-data; name="careerFile"; filename="pikachu2.png"

< ./pikachu2.png

###자격 파일 수정
PUT http://localhost:8001/setting/certificateFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3NTcxMTg2MDE5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODQzNTE4Nn0.HEHwoPp45ZOnTxmS0mJf6E5EHIIArnTP5Vb-NuJitZY

--WebAppBoundary
Content-Disposition: form-data; name="cerAtcCode";

1
--WebAppBoundary
Content-Disposition: form-data; name="certificateFile"; filename="pikachu2.png"

< ./pikachu2.png


###급여 통장 파일 수정
PUT http://localhost:8001/setting/salaryFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3NTcxMTg2MDE5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODQzNTE4Nn0.HEHwoPp45ZOnTxmS0mJf6E5EHIIArnTP5Vb-NuJitZY

--WebAppBoundary
Content-Disposition: form-data; name="salAtcCode";

6
--WebAppBoundary
Content-Disposition: form-data; name="salCode";

sal1
--WebAppBoundary
Content-Disposition: form-data; name="salaryFile"; filename="pikachu2.png"

< ./pikachu2.png


###연차 업데이트
PUT http://localhost:8001/setting/updateVacation
Content-Type: application/json;
Accept: */*

{
  "memCode": 4,
  "vctCount": 3
}

###전체 직원 근태 조회
POST http://localhost:8001/setting/attendance
Content-Type: application/json;
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3NTQxNjUxOTE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJtZW1FbWFpbCI6InN1anVuZ0BnbWFpbC5jb20iLCJtZW1Db2RlIjoxLCJtZW1OYW1lIjoi7J2064-Z6529IiwibWVtUm9sZSI6IuydvOuwmOyCrOybkCIsImV4cCI6MTcwODQwNTY1MX0.cv_yv5ey_mD8lIqO3IvkAIaWys5aln4eJt2exykuPPs


{
  "yearMonth": "2024-02"
}