### 직원 정보 등록 - 인사정보 + 사진
POST http://localhost:8001/member/member
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="memName"

노연지

--WebAppBoundary
Content-Disposition: form-data; name="memPhone"

010-8760-8336

--WebAppBoundary
Content-Disposition: form-data; name="memEmail"

djddd@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="memAddress"

경기도 고양시

--WebAppBoundary
Content-Disposition: form-data; name="memBirth"

1991-01-20

--WebAppBoundary
Content-Disposition: form-data; name="memPassword"

0000

--WebAppBoundary
Content-Disposition: form-data; name="memHireDate"

2024-01-29

--WebAppBoundary
Content-Disposition: form-data; name="memStatus"

N

--WebAppBoundary
Content-Disposition: form-data; name="memRoll"

일반사원

--WebAppBoundary
Content-Disposition: form-data; name="posCode"

3

--WebAppBoundary
Content-Disposition: form-data; name="depCode"

5


### 직원 조회
GET http://localhost:8001/member/allMemberSearch?offset=1
Content-Type: application/json
Accept: */*

###직원 검색어로 조회
GET http://localhost:8001/member/search?s=이
Content-Type: application/json
Accept: */*

###직원등록 -부서 조회
GET http://localhost:8001/member/depSearch
Content-Type: application/json
Accept: */*


###직원등록 -직급 조회
GET http://localhost:8001/member/position
Content-Type: application/json
Accept: */*

###학위정보등록
POST http://localhost:8001/member/insertDegree
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "degKind": "학사",
  "degMajor": "공학",
  "degName": "서울대학교",
  "degGraduation": "2024-01-31",
  "degState":"졸업",
  "degAdmissions": "2020-01-01"
}

###자격정보등록
POST http://localhost:8001/member/insertCertificate
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "cerName": "컴퓨터활용능력",
  "cerKind": "2급",
  "cerDay": "2024-01-31",
  "cerEndDate": null,
  "cerDescription": "비고",
  "cerInstitution": "대한상공회의소"
}

###경력정보등록
POST http://localhost:8001/member/insertCareer
Content-Type: application/json
Accept: */*

{
  "memCode": 240129002,
  "crrName": "회사명",
  "crrPosition": "대리",
  "crrStartDate": "2017-01-01",
  "crrEndDate": "2020-01-01",
  "crrState": "Y",
  "crrDescription" : "비고"
}


###직원인사정보조회 - 학위, 경력, 자격
GET http://localhost:8001/member/searchResourcesInformation?mem=1
Content-Type: application/json
Accept: */*

//직원수정(상세조회 -> 업데이트)
//직원인사정보수정
//직원서류함등록
//직원서류함수정
//연차 조회
//연차 업데이트