### 회원가입 테스트
POST http://localhost:8001/member/member
Content-Type: application/json    //multipart/form-data; boundary=WebAppBoundary
Accept: */*

{
  "mem_name": "술쟁이",
  "mem_phone": "010-0000-0000",
  "mem_email": "ohgiraffers@gmail.com",
  "mem_address": "종로하이미디어",
  "mem_birth": "7777-77-77",
  "mem_password": "pass01",
  "mem_hire_date": "7777-77-77",
  "mem_end_date": "",
  "mem_status": "",
  "mem_role": ""
}